include:
  - remote: 'https://gitlab.freedesktop.org/freedesktop/ci-templates/-/raw/145b1bc7ef1702d2bd71584010d7113c6786a506/templates/fedora.yml'
  - remote: 'https://gitlab.freedesktop.org/freedesktop/ci-templates/-/raw/34f4ade99434043f88e164933f570301fd18b125/templates/ci-fairy.yml'

stages:
 - review
 - prepare
 - build
 - test

variables:
  FDO_UPSTREAM_REPO: GNOME/libgxp

default:
  interruptible: true

workflow:
  rules:
    # Allow to switch from branch pipelines to MR pipelines seamlessly
    # https://docs.gitlab.com/ee/ci/jobs/job_control.html#avoid-duplicate-pipelines
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS && $CI_PIPELINE_SOURCE == "push"
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    # Don't trigger a branch pipeline if there is an open MR
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: '$CI_COMMIT_BRANCH'
    - if: '$CI_COMMIT_TAG'

.skip-git-clone:
  variables:
    GIT_STRATEGY: none

.only-merge-requests:
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^$/'
      when: never
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
      when: on_success

.pipeline-guard:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_TAG'
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - if: '$CI_COMMIT_BRANCH =~ /^gnome-[0-9-]+$/'
    # Avoid catchall `when: manual` rule which might
    # cause duplicate pipelines to be triggered.
    # https://docs.gitlab.com/ee/ci/jobs/job_control.html#avoid-duplicate-pipelines
    #
    # Also make it so pipelines without MR need to be started
    # manually, since their state will most likely be WIP
    - if: '$CI_COMMIT_BRANCH'
      when: 'manual'

repo-sanity:
  extends:
    - .fdo.ci-fairy
  stage: review
  variables:
    GIT_DEPTH: "1"
  script:
    - >
      if [[ -z "$CI_REGISTRY_IMAGE" ]] ;
      then
        .gitlab-ci/simple-junit-report.sh check-junit-report.xml \
          repo-sanity "The container registry should be enabled in the project general settings panel at $CI_PROJECT_URL/edit" ;
        exit 1 ;
      fi
  artifacts:
    expire_in: 1 week
    paths:
      - check-junit-report.xml
    reports:
      junit: check-junit-report.xml
  rules:
    - !reference [.only-merge-requests, rules]

check-merge-request:
  extends:
    - .fdo.ci-fairy
    - .skip-git-clone
  stage: review
  script:
    ci-fairy check-merge-request --require-allow-collaboration --junit-xml=check-merge-request-report.xml
  artifacts:
    expire_in: 1 week
    paths:
      - check-merge-request-report.xml
    reports:
      junit: check-merge-request-report.xml
  rules:
    - !reference [.only-merge-requests, rules]

.container-setup:
  variables:
    FDO_DISTRIBUTION_TAG: '2024-11-24.0'
    FDO_DISTRIBUTION_VERSION: 41
    FDO_DISTRIBUTION_PACKAGES:
      util-linux
      git
      dbus-daemon
      mutter
      xorg-x11-server-Xwayland
    FDO_DISTRIBUTION_EXEC: |
      dnf install -y 'dnf-command(builddep)'
      dnf builddep gtk4 -y

      ./.gitlab-ci/install-meson-project.sh \
        https://gitlab.gnome.org/GNOME/gtk.git \
        main . bccd0aa079eae54d2958032d8e5b008650b91ad7

prepare:
  extends:
    - .fdo.container-build@fedora
    - .container-setup
    - .skip-git-clone
  stage: prepare
  rules:
    - !reference [.pipeline-guard, rules]

build:
  extends:
    - .fdo.distribution-image@fedora
    - .container-setup
  stage: build
  script:
    - meson setup build .
    - meson compile -C build
  needs:
    - job: prepare
      artifacts: false
  artifacts:
    expire_in: 1 day
    paths:
      - build

test:
  extends:
    - .fdo.distribution-image@fedora
    - .container-setup
  stage: test
  variables:
    XDG_SESSION_TYPE: wayland
  script:
    - mkdir -m 1777 /tmp/.X11-unix
    - env XDG_RUNTIME_DIR=$(mktemp -d --tmpdir gxdp-runtime-XXXXXX)
        meson test
          -C build
          --no-rebuild
          --print-errorlogs
  needs:
    - job: build
  artifacts:
    reports:
      junit: "build/meson-logs/testlog.junit.xml"
